### ISSUE TITLE
Mauvaise interface à l'install

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/openvpn_ynh#10]
Salut,

Après install, l'interface des iptables (wlan0) est différente de celle de mon VPS (venet0)
Je ne sais pas si c'est un problème de ton côté ou du côté de mon VPS.

Léo

**Comment by Kloadut** [comment]
Essaye de changer l'interface dans /etc/yunohost/interface et de réessayer l'install

**Comment by opi** [comment]
`/etc/yunohost/interface` file is not created anymore, so OpenVPN install script is broken.

**Comment by sbadia** [comment]
I take a look on this one :)

**Comment by rikmendes** [comment]
same here : Warning: cat: /etc/yunohost/interface: No such file or directory

**Comment by sbadia** [comment]
@rikmendes I know, I'm currently reworking on this app, but for the moment in a separate branch (devel), even if master is broken :smile_cat:

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/484

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
