### ISSUE TITLE
Unable to connect to openvpn

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/openvpn_ynh#11]
Hi
I am unable to connect through openvpn.
Here is the log containing error message.

https://datamol.in/zerobin/?d53d90ad75b17fbd#3vcPgsbkrDybOz/w4Ay26NNXqIRKPei4e5girAYLi5c=

**Comment by sbadia** [comment]
Hi @anmol26s , sorry for the delay, and thanks for this bug report, unfortunately the paste isn't available anymore, can you repost the error message?

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/483

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
