### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by Trowic** [YunoHost-Apps/openvpn_ynh#16]
Hi,

I've got a problem installing openvpn for yunohost.

I'm getting this error : 

    + sudo iptables -L
    iptables v1.4.14: can't initialize iptables table `filter': Permission denied (you must be root)

i'm installing via moulinette, with `sudo yunohost app install openvpn`. Even with the root user i'm getting this error.
Any idea ?

**Comment by sbadia** [comment]
Hi @Trowic thanks for this bug report!
Sorry for the delay… I take a look.

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/482

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
