### ISSUE TITLE
Python error during the parse of manifest.json

### ISSUE THREAD

**Issue by SylvainCecchetto** [YunoHost-Apps/openvpn_ynh#32]
Hi,

During the installation I have an error when python is reading the manifest file.

If anybody know?

```
++ ynh_read_manifest url
++ '[' -f ../manifest.json ']'
++ ynh_read_json ../manifest.json url
++ sudo python3 -c 'import sys, json;print(json.load(open('\''../manifest.json'\''))['\''url'\''])'
Warning: Traceback (most recent call last):
Warning:   File "<string>", line 1, in <module>
Warning:   File "/usr/lib/python3.4/json/__init__.py", line 265, in load
Warning:     return loads(fp.read(),
Warning:   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
Warning:     return codecs.ascii_decode(input, self.errors)[0]
Warning: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 198: ordinal not in range(128)
+ export project_url=

```

**Comment by lapineige** [comment]
I didn't tried to install it (I already have it working) but after making a manifest.json file (with the same content), and running the same python3 commands, it works on my side.
The commands and result:
> python3 -c "import sys, json;print(json.load(open('manifest.json'))['url'])"
>> http://openvpn.net

and

> python3 -c "import sys, json;print(json.load(open('manifest.json'))['version'])"
>>2.3.4-3

**Comment by SylvainCecchetto** [comment]
Thanks lapineige, after a new test that seems to work ... I don't know why !
