### ISSUE TITLE
Could this app be installed?

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/openvpn_ynh#46]
Wether I can install OpenVPN on my server or not is a crucial point to me in deciding wether to use Yunohost or not. Could anyone share at what point is the implementation of this app?

Thanks a lot ❤️

**Comment by lapineige** [comment]
Judging by the lack of recent update and the multiples issues reported, I don't think you can expect a stable support.

But there is a WireGuard app https://forum.yunohost.org/t/wireguard-virtual-private-network/12928 https://github.com/YunoHost-Apps/wireguard_ynh if using specifically OpenVPN is not required.

**Comment by xplosionmind** [comment]
Thank you very much. I will use WireGuard instead.
